var NTPaypal=NTPaypal||{};NTPaypal.compatibilityTest=function(){return"function"!=typeof Promise||"function"!=typeof fetch?!1:!0};if(!NTPaypal.compatibilityTest())throw Error("Browser not supported ; please use Edge > 14, Chrome, Firefox, Safari > 10.1");
NTPaypal.Product=function(a,b,c,d,e){e=e||{};this.title=a;this.price=Number.parseFloat(b);this.category=c;this.tax=Number.parseFloat(e.tax)||0;this.description=e.description||"";this.sku=e.sku||"";this.currency_code=d;if(!this.title)throw Error("'title' parameter of 'Product' constructor not set");if("undefined"==typeof b)throw Error("'price' parameter of 'Product' constructor not set");if("undefined"==typeof c)throw Error("'category' parameter of 'Product' constructor not set");if(!this.currency_code)throw Error("'currency_code' parameter of 'Product' constructor not set");
};NTPaypal.Product.fromJson=function(a){if("object"!=typeof a)throw new TypeError("'obj' parameter of 'Product.fromJson' static method is not an object litteral");var b=Object.create(NTPaypal.Product.prototype);b.title=a.title;b.price=a.price;b.category=a.category;b.tax=a.tax;b.description=a.description;b.sku=a.sku;b.currency_code=a.currency_code;return b};
NTPaypal.Product.prototype.toPaypalItem=function(){return{name:this.title,unit_amount:{currency_code:this.currency_code,value:this.price},tax:{currency_code:this.currency_code,value:this.tax},description:this.description,sku:this.sku,category:this.category}};NTPaypal.Product.prototype.setTax=function(a){this.tax=a;return this};NTPaypal.Product.prototype.setSku=function(a){this.sku=a;return this};NTPaypal.Product.prototype.withDescription=function(a){this.description=a;return this};
NTPaypal.Product.prototype.setQuantity=function(a){return new NTPaypal.ProductQuantity(this,a)};NTPaypal.ProductQuantity=function(a,b){if(!(a instanceof NTPaypal.Product))throw new TypeError("'item' parameter of 'ProductQuantity' constructor is not a Product instance");this.product=a;this.quantity=Number.parseInt(b)||0};
NTPaypal.ProductQuantity.fromJson=function(a){if("object"!=typeof a)throw new TypeError("'obj' parameter of 'ProductQuantity.fromJson' static method is not an object litteral");if(!a.product||!a.product.sku)throw Error("'sku' property for product '"+a.product.title+"' is mandatory when creating ProductQuantity object");var b=Object.create(NTPaypal.ProductQuantity.prototype);b.product=NTPaypal.Product.fromJson(a.product);b.quantity=a.quantity;return b};
NTPaypal.ProductQuantity.prototype.toPaypalItem=function(){var a=this.product.toPaypalItem();a.quantity=this.quantity;return a};
NTPaypal.Customer=function(a,b){b=b||{};if(!a)throw Error("'firstname' parameter of 'Customer' constructor not set");if(b.city||b.zipcode||b.countrycode)if(!b.city||!b.zipcode||!b.countrycode)throw Error("'other.city', 'other.zipcode' and 'other.countrycode' parameters of 'Customer' constructor not set");this.firstname=a;this.surname=b.surname||"";this.address1=b.address1||"";this.address2=b.address2||"";this.zipcode=b.zipcode||"";this.city=b.city||"";this.countrycode=b.countrycode||"";this.email=
b.email||"";this.phone=b.phone||"";this.phone_type=b.phone_type||""};NTPaypal.Customer.prototype.toPaypalShipping=function(){var a={name:{full_name:(this.firstname+" "+this.surname).trim()},type:"SHIPPING"};this.city&&this.zipcode&&this.countrycode&&(a.address={address_line_1:this.address1,address_line_2:this.address2,admin_area_2:this.city.toUpperCase(),postal_code:this.zipcode,country_code:this.countrycode});return a};
NTPaypal.Customer.prototype.named=function(a,b){this.firstname=a;this.surname=b;return this};NTPaypal.Customer.prototype.living=function(a,b){this.address1=a;this.address2=b;return this};NTPaypal.Customer.prototype["in"]=function(a,b,c){this.zipcode=a;this.city=b;this.countrycode=c;return this};NTPaypal.Customer.prototype.withPhone=function(a,b){this.phone=a;this.phone_type=b;return this};NTPaypal.Customer.prototype.withEmail=function(a){this.email=a;return this};
NTPaypal.Inventory=function(a){if("object"==typeof a&&"Array"!=a.constructor.name)throw new TypeError("'items' parameter of 'Inventory' constructor is not an array");if(a.length&&!(a[0]instanceof NTPaypal.ProductQuantity))throw new TypeError("'items' parameter of 'Inventory' constructor is not an array of ProductQuantity objects");this.items=a||[]};
NTPaypal.Inventory.fromJson=function(a){if("object"!=typeof a)throw new TypeError("'obj' parameter of 'Inventory.fromJson' static method is not an object litteral");var b=Object.create(NTPaypal.Inventory.prototype);b.items=a.items.map(function(c){return NTPaypal.ProductQuantity.fromJson(c)});return b};NTPaypal.Inventory.prototype.empty=function(){this.items=[]};NTPaypal.Inventory.prototype.count=function(){return this.items.length};
NTPaypal.Inventory.prototype.add=function(a,b){if(!(a instanceof NTPaypal.Product))throw new TypeError("'item' parameter of 'Inventory.add' method is not an instance of 'Product'");b=b||1;try{var c=this.get(a.sku);c.quantity+=b}catch(d){this.items.push(new NTPaypal.ProductQuantity(a,b))}};NTPaypal.Inventory.prototype.remove=function(a){for(var b=this.items.length,c=0;c<b;c++)if(this.items[c].product.sku==a){this.items.splice(c,1);break}};
NTPaypal.Inventory.prototype.setQuantity=function(a,b){this.get(a).quantity=Number.parseInt(b)};NTPaypal.Inventory.prototype.get=function(a){for(var b=this.items.length,c=0;c<b;c++)if(this.items[c].product.sku==a)return this.items[c];throw Error("Item with sku='"+a+"' not found in inventory");};NTPaypal.Inventory.prototype.getContent=function(){return this.items};NTPaypal.Inventory.prototype.contains=function(a){for(var b=this.items.length,c=0;c<b;c++)if(this.items[c].product.sku==a)return!0;return!1};
NTPaypal.Cart=function(a){this.inventory=new NTPaypal.Inventory(a)};NTPaypal.Cart.fromJson=function(a){if("string"!=typeof a)throw new TypeError("'jsonString' parameter of 'Cart.fromJson' static method is not a string");a=JSON.parse(a);var b=Object.create(NTPaypal.Cart.prototype);b.inventory=NTPaypal.Inventory.fromJson(a.inventory);return b};NTPaypal.Cart.prototype.empty=function(){return this.inventory.empty()};NTPaypal.Cart.prototype.count=function(){return this.inventory.count()};
NTPaypal.Cart.prototype.add=function(a,b){return this.inventory.add(a,b)};NTPaypal.Cart.prototype.remove=function(a){return this.inventory.remove(a)};NTPaypal.Cart.prototype.setQuantity=function(a,b){return this.inventory.setQuantity(a,b)};NTPaypal.Cart.prototype.get=function(a){return this.inventory.get(a)};NTPaypal.Cart.prototype.contains=function(a){return this.inventory.contains(a)};NTPaypal.Cart.prototype.getContent=function(){return this.inventory.getContent()};
NTPaypal.Cart.prototype.toPaypalItems=function(){for(var a=[],b=this.count(),c=0;c<b;c++)a.push(this.inventory.items[c].toPaypalItem());return a};
NTPaypal.Order=function(a,b,c){c=c||{};if(!(a instanceof NTPaypal.Cart))throw new TypeError("'cart' parameter of 'Order' constructor is not an instance of 'Cart'");if("object"==typeof c.customer&&!(c.customer instanceof NTPaypal.Customer))throw new TypeError("'other.customer' parameter of 'Order' constructor is not an instance of 'Customer'");if(c.customer&&"object"!=typeof c.customer)throw new TypeError("'other.customer' parameter of 'Order' constructor is not an instance of 'Customer'");if(!b)throw Error("'currency_code' parameter of 'Order' constructor not set");
this.customer=c.customer||null;this.cart=a;this.currency_code=b;this.shipping=Number.parseFloat(c.shipping)||0;this.description=c.description||"";this.custom_id=c.custom_id||null};
NTPaypal.Order.prototype.toPurchaseUnit=function(){for(var a=this.cart.toPaypalItems(),b=a.length,c=0,d=0,e=0;e<b;e++)c+=a[e].quantity*a[e].unit_amount.value,d+=a[e].quantity*a[e].tax.value;a={items:a,description:this.description,amount:{currency_code:this.currency_code,value:Number.parseFloat(c+d+this.shipping).toFixed(2),breakdown:{item_total:{currency_code:this.currency_code,value:Number.parseFloat(c).toFixed(2)},tax_total:{currency_code:this.currency_code,value:Number.parseFloat(d).toFixed(2)},
shipping:{currency_code:this.currency_code,value:Number.parseFloat(this.shipping).toFixed(2)}}}};this.customer&&(a.shipping=this.customer.toPaypalShipping());this.custom_id&&(a.custom_id=this.custom_id);return a};NTPaypal.Shop=function(a,b,c){if(!a)throw Error("'currency_code' parameter of 'Shop' constructor not set");this.currency_code=a;this.shopid=b||"NTPaypal.Shop";this.shopname=c||""};NTPaypal.Shop.prototype.newProduct=function(a,b,c,d){return new NTPaypal.Product(a,b,c,this.currency_code,d)};
NTPaypal.Shop.prototype.newProductQuantity=function(a,b){return new NTPaypal.ProductQuantity(a,b)};NTPaypal.Shop.prototype.newCustomer=function(a,b){return new NTPaypal.Customer(a,b)};NTPaypal.Shop.prototype.newOrder=function(a,b){return new NTPaypal.Order(a,this.currency_code,b)};NTPaypal.Shop.prototype.newCart=function(a){return new NTPaypal.Cart(a)};
NTPaypal.Shop.prototype.expressButtons=function(a,b,c,d){return this.paypalButtons(this.newOrder(this.newCart([this.newProductQuantity(this.newProduct(a,b,c||"PHYSICAL_GOODS"),1)])),d)};
NTPaypal.Shop.prototype.paypalButtons=function(a,b,c){try{if(!(a instanceof NTPaypal.Order))throw new TypeError("'order' parameter of 'Shop.paypalButton' function is not an instance of 'Order'");if(!b)throw Error("'selector' parameter of 'Shop.paypalButton' function not set");var d={};d.purchase_units=[a.toPurchaseUnit()];c&&(d.application_context=c);a.customer&&(a.customer.email&&(d.payer=d.payer||{},d.payer.email_address=a.customer.email),a.customer.phone&&(d.payer=d.payer||{},d.payer.phone={phone_number:{national_number:a.customer.phone}},
a.customer.phone_type&&(d.payer.phone.phone_type=a.customer.phone_type)));return new Promise(function(e,g){paypal.Buttons({createOrder:function(h,f){return f.order.create(d)},onApprove:function(h,f){return f.order.capture().then(e)},onCancel:g,onError:g}).render(b)})}catch(e){return Promise.reject(e)}};NTPaypal.Shop.prototype.product=NTPaypal.Shop.prototype.newProduct;NTPaypal.Shop.prototype.quantityOf=function(a,b){return this.newProductQuantity(b,a)};NTPaypal.Shop.prototype.customer=function(){return new NTPaypal.Customer("no name")};
NTPaypal.Shop.prototype.sell=function(a){var b=new NTPaypal.Sale(this);if("object"==typeof a&&a instanceof NTPaypal.Cart)return b.cart=a,b;"object"==typeof a&&a instanceof NTPaypal.Product&&(a=[this.newProductQuantity(a,1)]);"object"==typeof a&&a instanceof NTPaypal.ProductQuantity&&(a=[a]);if("object"!=typeof a||"Array"!=a.constructor.name)throw new TypeError("'items' parameter of 'Shop.sell' method is not an array");if(a.length&&!(a[0]instanceof NTPaypal.ProductQuantity))throw new TypeError("'items' parameter of 'Shop.sell' method is not an array of ProductQuantity objects");
b.cart=this.newCart(a);return b};NTPaypal.Sale=function(a){this.shop=a;this.customer=this.cart=null;this.shipping=0;this.description="";this.custom_id=null};NTPaypal.Sale.prototype.to=function(a){if(a&&!(a instanceof NTPaypal.Customer))throw new TypeError("'customer' parameter of 'Sale.to' method is not an instance of 'Customer'");this.customer=a;return this};NTPaypal.Sale.prototype.withShipping=function(a){this.shipping=Number.parseFloat(a);return this};
NTPaypal.Sale.prototype.withDescription=function(a){this.description=a;return this};NTPaypal.Sale.prototype.withCustom_id=function(a){this.custom_id=a;return this};NTPaypal.Sale.prototype.payButtonsInside=function(a){if("string"!=typeof a)throw new TypeError("'selector' parameter of 'Sale.payButtonsInside' method is not a string");if(!a)throw new TypeError("'selector' parameter of 'Sale.payButtonsInside' method is not set");return new NTPaypal.Payment(a,this)};
NTPaypal.Payment=function(a,b){this.sale=b;this.selector=a;this.application_context=null};NTPaypal.Payment.prototype.set=function(a,b){if(!a||"string"!=typeof a)throw new TypeError("'key' parameter of 'Payment.set' method is not set or not of type 'string'");this.application_context=this.application_context||{};this.application_context[a]=b;return this};
NTPaypal.Payment.prototype.withApplicationContext=function(a){if("object"!=typeof a)throw new TypeError("'values' parameter of 'Payment.withApplicationContext' method is not an object");this.application_context=a;return this};
NTPaypal.Payment.prototype.execute=function(){var a={};this.sale.customer&&(a.customer=this.sale.customer);this.sale.shipping&&(a.shipping=this.sale.shipping);this.sale.description&&(a.description=this.sale.description);this.sale.custom_id&&(a.custom_id=this.sale.custom_id);return this.sale.shop.paypalButtons(this.sale.shop.newOrder(this.sale.cart,a),this.selector,this.application_context)};